### ISSUE TITLE
Consent Review is horizontally scrollable

### ISSUE THREAD

**Issue by p2** [ResearchKit/ResearchKit#243]
This is present in latest master and seems to have been introduced with merge c42f29f from May 8: The consent document in the consent review step is horizontally scrollable, see screenshot.

![screen shot 2015-06-01 at 13 23 21](https://cloud.githubusercontent.com/assets/358485/7918752/9f17995a-0861-11e5-80aa-735edaf28727.png)

**Comment by jwe-apple** [comment]
Which task is this in? I'm not seeing this behavior in ORKCatalog, for instance.

**Comment by jwe-apple** [comment]
Or - could you supply the content you're using?

**Comment by p2** [comment]
This is out of AppCore, noticed this happening when pulling latest master of ResearchKit, then going back until it would be back to "normal". The page I'm using is a stand-in and only contains:

```html
<!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		
		<title>Consent</title>
		<link href="Consent.css" rel="stylesheet" type="text/css" />
	</head>
	<body>
		<div class="container">
			<div class="content">
				<h1>Consent</h1>
				
				<p>Full consent.</p>
			</div>
		</div>
	</body>
</html>
```

```css
html, body {
	margin: 0; padding: 0;
}
body {
	font-family: "Helvetica Neue", 'HelveticaNeue', 'HelveticaNeue'; font: -apple-system-body;
}
```
